image: cypress/browsers:node14.15.0-chrome86-ff82

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
    - ls -lah public/
  artifacts:
    paths:
      - public/

test:lint:
  stage: test
  dependencies:
    - build
  script:
    - ls -lah public/
    - npm install --include=dev
    - npm run lint

#test:lighthouse:
#  stage: test
#  dependencies:
#    - build
#  script:
#    - ls -lah public/
#  # Uncomment when running and testing this pipeline locally. The build occurs earlier in the pipeline when running on
## GitLab, however, it does not local. Thus you have to run it as part of this job
##    - npm run build
#    - npm install --include=dev
#    - npm run lighthouse
#    - ls -lah .lighthouseci/
#  artifacts:
#    paths:
#      - .lighthouseci/*.html
