image: cypress/browsers:node12.18.3-chrome83-ff77

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/

test:lint:
  stage: test
  dependencies:
    - build
  script:
    - npm install --include=dev
    - npm run lint

test:lighthouse:
  stage: test
  dependencies:
    - build
  script:
# Uncomment when running and testing this pipeline locally. The build occurs earlier in the pipeline when running on
# GitLab, however, it does not local. Thus you have to run it as part of this job
#    - npm run build
    - npm install --include=dev
    - npm run lighthouse
    - ls -lah .lighthouseci/
  artifacts:
    paths:
      - .lighthouseci/*.html

deploy:staging:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  dependencies:
    - build
  script:
    - aws s3 sync public s3://${STAGING_BUCKET_NAME} --delete
    - aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths "/*"
  environment:
    name: staging
    url: https://staging.jonbeckman.com
  only:
    - inflight

deploy:production:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  dependencies:
    - build
  script:
    - aws s3 sync public s3://${PROD_BUCKET_NAME} --delete
    - aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --paths "/*"
  environment:
    name: production
    url: https://jonbeckman.com
  only:
    - master
