image: cypress/browsers:node12.18.3-chrome83-ff77

stages:
  - build
  - test
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run build

test:lint:
  stage: test
  script:
    - npm run lint

test:lighthouse:
  stage: test
  script:
    - npm install -g @lhci/cli@0.5.0 gatsby-cli@2.12.109
    - lhci autorun --collect.start-server-command="gatsby serve" --collect.url=http://localhost:9000/ --upload.target=filesystem --upload.outputDir=lighthouse-reports --collect.settings.chromeFlags="--no-sandbox"
    - ls -lah
    - ls -lah lighthouse-reports/

deploy:staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.jonbeckman.com
  only:
    - inflight

deploy:production:
  stage: deploy
  script:
    - npm run deploy
  environment:
    name: production
    url: https://jonbeckman.com
  only:
    - master
